[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "macroser_stalker320"
version = "0.0.2"
authors = [
    { name = "stalker320", email="stalker3204@yandex.com" }
]
description = "alternative preprocessor for C"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
